name: Secret Scan

on:
  push:
    branches: [ master, main, development ]
  pull_request:
    branches: [ master, main, development ]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run secret scan script
      run: |
        python3 scan_devsecops_repo.py
