name: Secret Scan with Gitleaks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    name: Run Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""
          fail: true
